### PR TITLE
Add multi-thread support for AM3

### PR DESCRIPTION
**Pull request by ArthurGarnier**
When lots of request are done on the server some connections are closed due to the single thread. 
This option allows multi-thread XMLRPC server

### CODE REVIEW

**Comment by tcmitchell** [comment]
First and foremost, Thank You! This is a great contribution, thanks for taking the time to submit it.

I have two suggestions for you:

* Please add your name and organization to CONTRIBUTORS.md and include that change in this pull request. That way people will know you helped out.
* Should the variable `multithread` be initialized to `False` instead of `None`? There are two places where it is initialized to `None`. I think the functionality won't change, but I think the code would be clearer to have it initialized to the default value instead of chasing down if something different happens when it is set to `None`

Let us know about those two changes, either by updating the pull request or a comment here, or both.

Thanks again!

**Comment by ArthurGarnier** [comment]
You're welcome, this project helped me a lot for the [Docker AM](https://github.com/ArthurGarnier/bootstrap-geni-am) implementation, so I'm happy to contribute !

* Done
* The behavior is the same between None and False, but indeed it's more clear with False.

**Comment by tcmitchell** [comment]
Thanks for the updates, this all looks great. I'm sorry I overlooked this, but there's just (I think) one more thing:

* Please add an entry in CHANGES for this change. You can use the title of this pull request for the text description, and this pull request number for the number.

I think with the CHANGES squared away, I'll be able to merge this in. Very sorry I forgot about that until now. Again, thanks!

**Comment by ArthurGarnier** [comment]
Hello,
It's done, sorry for the delay !

**Comment by tcmitchell** [comment]
Sorry for the delay on this end. It's all merged now.

**Pull request merged**
