### PR TITLE
Allow deployments to specify delegate to use in the config file...

### PR DESCRIPTION
**Pull request by dmargery**
for v3 Aggregate Managers. 

This pull request is incomplete, but I'm waiting for merge of 836 to update the CHANGELOG to avoid conflicts in merges.

David

### CODE REVIEW

**Comment by ahelsing** [comment]
Doesn't `parse_args` need to define the `--delegate` option?

Would it be more convenient to allow specifying the delegate in the `gcf_config` file?

**Comment by dmargery** [comment]
I've updated the patch with proper CHANGES. It is now possible to specify the delegate either from command line of gcf_config, with standard precedence of command-line of config file.

David

**Comment by ahelsing** [comment]
I don't see the change to get the delegate class name from `gcf_config`?

I think the code in `gcf-am.py` to launch with a delegate needs to be something like this:
```python
    if hasattr(opts, 'delegate') and opts.delegate is not None and str(opts.delegate).strip() != "":
```
(Otherwise you get an exception if you do not supply a delegate.)

It looks like this code assumes that new delegates have a unique set of arguments, not the same as the arguments to the `ReferenceAggregateManager`. Is there a reason for this difference? I'd prefer to use the same arguments in the reference implementation. 

While we're there, should we have a base class that both the `ReferenceAggregateManager` and new delegates extend? (in the process, better defining the arguments to the init() function in a consistent way)

**Comment by dmargery** [comment]
The code you seem to be looking for starts line 156. 

I agree it could do with a try catch to output a nicer error message if the delegate code can not be found. I'll see if I can squeeze the time today to add this to the pull request.

I had not paid attention that in the patch, I pass a richer set of parameters to the constructor as expected by the `ReferenceAggregateManager`. I'll think about this.

I my case, I'm interested in deriving the `ReferenceAggregateManager`, and reusing the code it has to check access rights and call parameters. Maybe I'll end up with enough experience to understand what should be moved in an `AbstractAggragateManager`, but it is too early for me to usefully suggest such an implementation.

David

**Comment by ahelsing** [comment]
Is it possible you haven't updated the pull request with all your changes? I think I'm not seeing what you're seeing. I see the piece you just added to catch the exception. But I don't see anything reading the delegate from the `gcf_config` file.

Have you tried running the AM and trying to use the ReferenceAggregateManager as is? I think we need some of the changes I suggested to check properly handle not supplying a delegate and falling back on the ReferenceAggregateManager.

As for the abstraction, it could simply be something like `am1.AggregateManager` (with signatures updated for the APIv3 methods). That is, a class that simply defines the functions that are the API methods, with an initializer defining the constructor arguments.

As for the arguments to the constructor:
The current reference takes `root_cert, urn_authority, url`. Your new delegate takes `trusted_roots, urn_authority, url, root_cert`. How about we change your delegate to `root_cert, urn_authority, url, trusted_roots=None`, and also change the ReferenceAggregateManager to add that `trusted_roots=None` argument? Then the 2 match, and the last argument is optional.

**Comment by dmargery** [comment]
When I look at the diff tab of this pull request, the second blob (for  src/gcf-am.py) has new code as from line 155. I wonder why you would not see these changes ? 

In the code I look at, the current reference takes `trusted_roots, urn_authority, url`. I've added a root_cert param, but I'm working on passing opts as kwargs, so we have something very extensible (people writing new delegates can add options in the aggregate-manager section of their config file, and have access to them from the constructor).

**Comment by dmargery** [comment]
From the tests I've done
* fails with an error message : bogus delegate specified in config file or on command line :ok_hand: 
* starts a specific delegate: when specified on the command line or in the config file :ok_hand: 
* fails when no delegate specified :no_good:

**Comment by dmargery** [comment]
starts `ReferenceAggregateManager` when no delegate specified :ok_hand: 

Sorry about the confusion about the behaviour of OptionParse and therefore my badly scoped answers.

**Comment by ahelsing** [comment]
This looks better. Thanks for the changes.

I tried:
```
$ python src/gcf-am.py --debug -D gcf.geni.am.am3.ReferenceAggregateManager -V3
```
And got:
```
  File "/ahelsing/GENI/gcf/src/gcf/geni/auth/util.py", line 55, in getInstanceFromClassname
    object_instance = class_instance(*argv,**kwargs)
TypeError: __init__() got an unexpected keyword argument 'certfile'
```

I think we need to add `**kwargs` as the last argument to the `ReferenceAggregateManager` constructor.

Additionally, we can allow delegates to work for APIv2 by simply adding the delegate argument to am2.py's `AggregateManagerServer`, and adding the `**kwargs` argument to it's `ReferenceAggregateManager`.

Thoughts?

**Comment by tcmitchell** [comment]
Your CHANGES say "Allow deployments to specify delegate to use in the config file". I think Aaron is looking for some code that actually reads the delegate from the configuration file. Something like:

```python
delegate = config[SECTION]['delegate']
```

That would probably be a fallback if the delegate is not specified on the command line.

Or did you not intend to include that functionality? If that's the case, perhaps update the CHANGES file so it doesn't mention loading the delegate from the config file.

**Comment by dmargery** [comment]
@tcmitchell : the delegate option is part of the aggregate-manager section of the config file. It is therefore read in through the generic mechanism in line 106: 

`for (key,val) in config['aggregate_manager'].items()`. 

As I did not know `OptionParser` well enough, I had not realized that if an option is defined by OptionParser and not set on the command-line, it is set in the result of `parse_args`. I believe this topic is cleared, and I can assure you that testing shows values are read from the config file.

**Comment by dmargery** [comment]
@ahelsing : Corrected the issues you found when creating the `ReferenceAggregateManager` on the command line, and added support for delegate specification for AMv2 code path.

**Comment by tcmitchell** [comment]
Thanks for clearing up the config file issue. I'm sorry I missed that.

**Comment by ahelsing** [comment]
This looks really nice now. I'm adding a little documentation to `README.txt` and `gcf_config.sample` and whatnot, and merging this in.

**Pull request merged**
