### PR TITLE
Add RPM packaging, update distributed files

### PR DESCRIPTION
**Pull request by tcmitchell**
* Add RPM packaging by:
 * adding geni-tools.spec
 * adding documentation to README-packaging.md
* Update the set of files that are distributed and incorporated into the packages

### CODE REVIEW

**Comment by ahelsing** [comment]
perhaps add a note in the CHANGES file?

**Comment by tcmitchell** [comment]
> perhaps add a note in the CHANGES file?

Whoops! Of course.

**Comment by ahelsing** [comment]
Add the pull request # to the line in the CHANGES file, please.

**Comment by tcmitchell** [comment]
Done.

**Pull request merged**
